version: "3.8"

services:
  redis:
    image: redis:latest
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - 6378:6379
  web:
    build: .
    command: bash -c "cd app && python -m daphne -p 8000 -b 0.0.0.0 webScrapingTest.asgi:application"
    volumes:
      - .:/usr/src/app/
    ports:
      - 8000:8000
    # env_file:
      # - ./.env
    depends_on:
      - redis
  celery:
    build: .
    command: bash -c "cd app && celery -A webScrapingTest worker -l info -E"
    volumes:
      - .:/usr/src/app/
    # env_file:
      # - ./.env
    depends_on:
      - redis
