# Generated by Django 4.0 on 2021-12-24 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textSpin', '0003_singlekeywordreport_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singlekeywordreport',
            name='article_body',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='singlekeywordreport',
            name='article_title',
            field=models.TextField(null=True),
        ),
    ]
