# Generated by Django 4.0 on 2021-12-28 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('textSpin', '0006_singlekeywordreport_article_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singlekeywordreport',
            name='article_url',
            field=models.CharField(default=0, max_length=2048, null=True),
        ),
        migrations.CreateModel(
            name='ArticleImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_1', models.CharField(max_length=1024)),
                ('image_2', models.CharField(max_length=1024)),
                ('image_3', models.CharField(max_length=1024)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='textSpin.singlekeywordreport')),
            ],
        ),
    ]
