# Generated by Django 4.0 on 2021-12-28 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textSpin', '0007_alter_singlekeywordreport_article_url_articleimages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articleimages',
            name='image_1',
        ),
        migrations.RemoveField(
            model_name='articleimages',
            name='image_2',
        ),
        migrations.RemoveField(
            model_name='articleimages',
            name='image_3',
        ),
        migrations.AddField(
            model_name='articleimages',
            name='path_image_1',
            field=models.CharField(default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='articleimages',
            name='path_image_2',
            field=models.CharField(default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='articleimages',
            name='path_image_3',
            field=models.CharField(default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='articleimages',
            name='url_image_1',
            field=models.CharField(default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='articleimages',
            name='url_image_2',
            field=models.CharField(default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='articleimages',
            name='url_image_3',
            field=models.CharField(default='', max_length=1024),
        ),
    ]
